### ISSUE TITLE
Android studio 2.0 环境下编译失败

### ISSUE THREAD

**Issue by luthink** [CycloneAxe/phphub-android#10]
Error:(158, 0) Gradle DSL method not found: 'compile()'
Possible causes:<ul><li>The project 'phphub-android' may be using a version of Gradle that does not contain the method.
<a href="open.wrapper.file">Open Gradle wrapper file</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>

**Comment by callmepeanut** [comment]
是要把gradle插件版本更新吧，AS里有提示怎么做的
