### ISSUE TITLE
这个错误该怎么解决？

### ISSUE THREAD

**Issue by a1018875550** [CycloneAxe/phphub-android#14]
Error:(27, 1) A problem occurred evaluating project ':app'.
> Could not find property 'APP_CLIENT_ID' on ProductFlavor_Decorated{name=main, dimension=null, minSdkVersion=ApiVersionImpl{mApiLevel=14, mCodename='null'}, targetSdkVersion=ApiVersionImpl{mApiLevel=22, mCodename='null'}, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptNdkModeEnabled=null, versionCode=1000, versionName=1.0.0, applicationId=org.estgroup.phphub, testApplicationId=null, testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={GIT_SHA=com.android.builder.internal.ClassFieldImpl@42026e1f}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}}.

**Comment by ChoingHyun** [comment]
met the same issue

**Comment by tianshaokai** [comment]
我已经改文件的名字，还是找不到这个APP_CLIENT_ID

**Comment by yufns** [comment]
遇到同样的问题!

**Comment by a1018875550** [comment]
2l is the right answer

**Comment by tianshaokai** [comment]
我已经试过了，还是不行

**Comment by yufns** [comment]
我也按照他修改的文件名,报同样的错误!

**Comment by a1018875550** [comment]
APP_CLIENT_ID=kHOugsx4dmcXwvVbmLkd
APP_CLIENT_SECRET=PuuFCrF94MloSbSkxpwS
API_ENDPOINT=https://staging_api.phphub.org/v1

JPUSH_CHANNEL=develop
JPUSH_APPKEY=

UMENG_APPKEY=

QQ_APPID=
QQ_APPKEY=

WX_APPID=
WX_SECRET=
com.android.build.gradle.overridePathCheck=true

-------------------------------------------------------------------------------------------------------------------
copy into the gradle.properties
