### ISSUE TITLE
com.facebook.fresco:fresco:0.7.0+ available for offline mode

### ISSUE THREAD

**Issue by 1074736711** [CycloneAxe/phphub-android#16]
提示这个错误，把版本改成0.9.0 依旧是报这个错，请看看
Error:No cached version listing for com.facebook.fresco:fresco:0.7.0+ available for offline mode.

**Comment by tianshaokai** [comment]
我也提示这个错误

**Comment by tianshaokai** [comment]
Error:Could not find any matches for com.umeng:fb:latest.integration as no versions of com.umeng:fb are available.
都是umeng 包报错

**Comment by bensonX** [comment]
基本都是这个问题

**Comment by yufns** [comment]
mavenCentral() 将这个库天骄到project的build.gradle中的buildscript->repositories就可以了

**Comment by linhaosheng** [comment]
Error:No cached version listing for com.facebook.fresco:fresco:0.7.0+ available for offline mode.

**Comment by Gongcong** [comment]
Error:No cached version listing for com.facebook.fresco:fresco:0.7.0+ available for offline mode.

**Comment by harman-ryanchen** [comment]
Error:No cached version listing for com.facebook.fresco:fresco:0.7.0+ available for offline mode.

**Comment by gzfgeh** [comment]
Error:No cached version listing for com.facebook.fresco:fresco:0.7.0+ available for offline mode.
