### ISSUE TITLE
fresco的问题

### ISSUE THREAD

**Issue by jokerknight** [CycloneAxe/phphub-android#19]
年前的时候还是能跑得起来的，后来经过检查发现是项目依赖的umeng的一个repo的问题，估计官方已经不再支持这个repo或者是什么原因。
这个项目如果不改这个地方根本跑不起来。

**Comment by CycloneAxe** [comment]
@jokerknight 多谢反馈 :beers:

**Comment by jokerknight** [comment]
@CycloneAxe 最后查出来问题是fresco 从jcenter中移除到mavenCentral了,需要在dependencies.gradle的repositories中加入 mavenCentral() ,另外我对你们项目中的mvp层级有些不清楚，为什么还要分出来一个model？还有就是代码为什么不剥离出一个framework层，全部放在一个项目中很容易会65535吧。

**Comment by CycloneAxe** [comment]
@jokerknight 
关于 model 主要是考虑到后期需要加入缓存的时候可以方便全局修改。

当前项目架构还不算合理，所以 mvp 层级等看着有些奇怪，项目中出现 65535 问题主要还是在引入的依赖包过多的情况下产生的，而当初构建这个项目的时候，希望尽可能的去采用开源的 library 来减少写出裹脚布般又臭又长的烂代码 😄 

如果您有更好的建议，愿闻其详 😜

**Comment by jokerknight** [comment]
@CycloneAxe  希望作者这个项目能往组件化方向发展，那样模块会更清晰，代码更简洁，对于gradle编译和开发效率上提升不是一点啊 。
然后作者尽量多加点注释，这个项目是个优质项目，always star focus~

**Comment by jokerknight** [comment]
@CycloneAxe  希望作者这个项目能往组件化方向发展，那样模块会更清晰，代码更简洁，对于gradle编译和开发效率上提升不是一点啊 。
然后作者尽量多加点注释，这个项目是个优质项目，always star focus~
