### ISSUE TITLE
有点不明白是怎么维护token的？

### ISSUE THREAD

**Issue by xiaolongyuan** [CycloneAxe/phphub-android#20]
1. api请求时 access_token过期  refresh_token 没过期 怎么自动处理？
2. api请求时 access_token过期  refresh_token 也过期 怎么处理？

**Comment by xiaolongyuan** [comment]
关于第一种注入的时候使用
```

    @Provides
    @Singleton
    @Named(AuthType.AUTH_TYPE_USER)
    TopicModel provideTopicModelByAuth(@ForApplication Context context, AccountManager accountManager, AuthAccountManager
            authAccountManager) {
        UserTokenProvider tokenProvider = new UserTokenProvider(context,accountManager,authAccountManager);
        return new TopicModel(context, tokenProvider);
    }

```
但是 access_token过期 怎么办？

**Comment by CycloneAxe** [comment]
@xiaolongyuan  参见此处 [https://github.com/CycloneAxe/phphub-android/blob/master/app/src/main/java/org/estgroup/phphub/common/transformer/RefreshTokenTransformer.java#L60](https://github.com/CycloneAxe/phphub-android/blob/master/app/src/main/java/org/estgroup/phphub/common/transformer/RefreshTokenTransformer.java#L60) 

如果 access_token 过期而 refresh_token 未过期，则刷新 access_token
如果 access_token 过期且 refresh_token 也过期，则重新申请 access_token
