### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by gzfgeh** [CycloneAxe/phphub-android#21]
Error:(27, 0) Could not find property 'APP_CLIENT_ID' on ProductFlavor_Decorated{name=main, dimension=null, minSdkVersion=ApiVersionImpl{mApiLevel=14, mCodename='null'}, targetSdkVersion=ApiVersionImpl{mApiLevel=22, mCodename='null'}, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptNdkModeEnabled=null, versionCode=1000, versionName=1.0.0, applicationId=org.estgroup.phphub, testApplicationId=null, testInstrumentationRunner=null, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={GIT_SHA=com.android.builder.internal.ClassFieldImpl@69e1e112}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}}.
<a href="openFile:/Users/guzhenfu/Downloads/phphub-android-master/app/build.gradle">Open File</a>

**Comment by CycloneAxe** [comment]
@gzfgeh 请确认 gradle.properties 内是否存在 APP_CLIENT_ID, gradle.properties 内容参见 [gradle.properties.example](https://github.com/CycloneAxe/phphub-android/blob/master/gradle.properties.example)

**Comment by gzfgeh** [comment]
有这个文件，还是不行
