### ISSUE TITLE
编译不通过，各种第三方包拉不下来

### ISSUE THREAD

**Issue by Casper3635** [CycloneAxe/phphub-android#22]
![Uploadi
![_20160602002246](https://cloud.githubusercontent.com/assets/3745303/15717195/7c04e1bc-2858-11e6-8309-c72d79ffd39f.png)
ng 微信截图_20160602002246.png…]()
唉，编译不通过，各种第三方库拉不下来，挺想运行起来学习一下结构的~ 蛋疼

**Comment by CycloneAxe** [comment]
@Casper3635  你修改了 build.gradle 文件吧
com.squareup.okhttp:okhttp-urlconnection:2.0.0 原来的版本指定的是 2.0.0
