### ISSUE TITLE
as2.1编译出错～

### ISSUE THREAD

**Issue by bbs7txt** [CycloneAxe/phphub-android#24]
`xecution failed for task ':app:transformResourcesWithMergeJavaResForFirRelease'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/maven/com.squareup.okio/okio/pom.xml`

**Comment by CycloneAxe** [comment]
测试没有问题，不过你可以在 [app/build.gradle#109](https://github.com/CycloneAxe/phphub-android/blob/master/app/build.gradle#L109) 追加下面的内容试试：

> exclude 'META-INF/maven/com.squareup.okio/okio/pom.xml'

**Comment by bbs7txt** [comment]
谢谢已经解决～
