### ISSUE TITLE
Error:(6, 0) CreateProcess error=2, 系统找不到指定的文件。

### ISSUE THREAD

**Issue by hejunbinlan** [CycloneAxe/phphub-android#25]
D:\workspace_studio2\phphub-android-master\app\build.gradle
Error:(6, 0) CreateProcess error=2, 系统找不到指定的文件。

第六行的内容为：
def gitSha = 'git rev-parse --short HEAD'.execute([], project.rootDir).text.trim()

**Comment by CycloneAxe** [comment]
Windows 下需要在环境变量中添加 Git\bin 路径，可以参照这篇文章 [Adding Git to Windows 7 Path](http://blog.countableset.ch/2012/06/07/adding-git-to-windows-7-path/) 进行设置
