### ISSUE TITLE
工程无法编译

### ISSUE THREAD

**Issue by AndroidLevi** [CycloneAxe/phphub-android#30]
Error:(27, 0) Could not find property 'APP_CLIENT_ID' on ProductFlavor_Decorated{name=main, dimension=null, minSdkVersion=ApiVersionImpl{mApiLevel=14, mCodename='null'}, targetSdkVersion=ApiVersionImpl{mApiLevel=22, mCodename='null'}, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptNdkModeEnabled=null, versionCode=1000, versionName=1.0.0, applicationId=org.estgroup.phphub, testApplicationId=null, testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={GIT_SHA=com.android.builder.internal.ClassFieldImpl@69e1e112}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}}.
<a href="openFile:E:\AndroidStudiioDemo\phphub-android-1.0.0\app\build.gradle">Open File</a>

**Comment by CycloneAxe** [comment]
Could not find property 'APP_CLIENT_ID'

请检查下你的 APP_CLIENT_ID 是否有定义

**Comment by skyyanyujiangnan** [comment]
同样的问题，怎么处理的

**Comment by CycloneAxe** [comment]
@skyyanyujiangnan 

麻烦贴下错误信息，如果和 @AndroidLevi 相同，请检查下 APP_CLIENT_ID 是否有定义

**Comment by skyyanyujiangnan** [comment]
Error:(18, 0) Could not get unknown property 'CLIENT_ID' for ProductFlavor_Decorated{name=main, dimension=null, minSdkVersion=DefaultApiVersion{mApiLevel=15, mCodename='null'}, targetSdkVersion=DefaultApiVersion{mApiLevel=24, mCodename='null'}, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=5, versionName=1.0.2, applicationId=com.jun.elephant, testApplicationId=null, testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}, mWearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.ProductFlavor.
<a href="openFile:E:\Summary\Elephant-master\Elephant-master\app\build.gradle">Open File</a>
是这样的，APP_CLIENT_ID 如何定义？

**Comment by CycloneAxe** [comment]
@skyyanyujiangnan 

2、复制 gradle.properties.example 为 gradle.properties 并编辑里面的相关信息

3、将项目导入 Android Studio 运行即可

**Comment by skyyanyujiangnan** [comment]
![image](https://cloud.githubusercontent.com/assets/13703216/23499088/a42d17b0-ff65-11e6-9ebc-ead73d668e6e.png)
您说的是这个吗？相关信息需要重新申请?

**Comment by skyyanyujiangnan** [comment]
Error:(22, 0) Could not find method android() for arguments [build_9mmqvhq6kve24kqx5lo58l2wo$_run_closure3@eeba6ab] on root project 'Elephant-master' of type org.gradle.api.Project.
<a href="openFile:E:\Summary\Elephant-master\Elephant-master\build.gradle">Open File</a>

出现了新问题

**Comment by CycloneAxe** [comment]
@skyyanyujiangnan 
先复制一份 gradle.properties.example 文件并重命名为 gradle.properties 即可，当前测试地址 https://staging.phphub.org/v1 可以访问

Error:(22, 0) Could not find method android() for arguments [build_9mmqvhq6kve24kqx5lo58l2wo$_run_closure3@eeba6ab] on root project 'Elephant-master' of type org.gradle.api.Project.

这个错误是运行[https://github.com/Freelander/Elephant](https://github.com/Freelander/Elephant) 这个项目产生的吧？

**Comment by skyyanyujiangnan** [comment]
嗯嗯，现在解决啦，所有的都换成24.0.2可以了
