### ISSUE TITLE
无法获取数据。

### ISSUE THREAD

**Issue by ZhouGongZaiShi** [CycloneAxe/phphub-android#32]
clone 下来，通过 Android Studio 编译至手机，无法获取数据。

**Comment by MagicYinuo** [comment]
我的也是无法获取数据 扫码登录提示405

**Comment by CycloneAxe** [comment]
@ZhouGongZaiShi 
@MagicYinuo 

sorry，之前接口做了次迁移，暂时关闭了 staging 服务。果断时间应该会开放 staging 服务
