### ISSUE TITLE
友盟maven库过期，无法找到

### ISSUE THREAD

**Issue by lecion** [CycloneAxe/phphub-android#6]
* dependencies.grade

    maven { url "https://raw.githubusercontent.com/umeng/mvn-repo-umeng/master/repository"}
已经过期，build时会抛出Bad Request

**Comment by CycloneAxe** [comment]
这个地址没有失效，你可以再试一次，如果还是无法构建成功，将 app/build.gradle 里的 'compile 'com.umeng:fb:latest.integration' 中的 "latest.integration" 修改为具体版本号，如 'compile 'com.umeng:fb:5.4.0' 试试

**Comment by lecion** [comment]
已经尝试过更改为具体版本号，仍旧出现同样错误，目前将友盟从项目中移除可以构建成功

**Comment by CycloneAxe** [comment]
@lecion 浏览器直接访问 https://raw.githubusercontent.com/umeng/mvn-repo-umeng/master/repository/com/umeng/fb/5.4.0/fb-5.4.0.aar 能否下载成功呢？
https://github.com/umeng/mvn-repo-umeng 这里是友盟的 mvn 仓库

**Comment by githubchen001** [comment]
http://dev.umeng.com/feedback/android/integration 去官网看下就立马解决
