### ISSUE TITLE
Nucleus + Dagger 2

### ISSUE THREAD

**Issue by NicodeLee** [CycloneAxe/phphub-android#8]
你好。请教个问题。
这边项目构建不通过。请问你是解决Nucleus + Dagger 2的问题呢？
在我的项目的基类使用
```
BaseActivity<PresenterType extends Presenter> extends NucleusAppCompatActivity<PresenterType>
```

**Comment by CycloneAxe** [comment]
Activity 子类需要在继承 BaseActivity<T> 后将 <T> 修改为具体的 Presenter 类，并且通过重载 injectorPresenter 方法实现对相应 Presenter 类的 Dagger 2 注入

**Comment by NicodeLee** [comment]
感谢回复，在 https://github.com/konmik/nucleus/issues/32 也看到

**Comment by NicodeLee** [comment]
【问题2】（列表页）跳转后返回，对应的Presenter会执行 onSave，然后会再次执行restartableLatestCache方法。看你代码是在Fragment（如：TopicFragment）用Icepick的@State定义InstanceState的key，按你的思路实现一次，没解决。是不是我忽略了那些步骤？

**Comment by CycloneAxe** [comment]
@NicodeLee  不是太明白您的疑惑在哪里？

**Comment by NicodeLee** [comment]
@CycloneAxe 问题的现象是：每次从列表页跳转到详情页面，列表Fragment对应的Presenter 会调用onCreate里面的restartableLatestCache方法。

**Comment by CycloneAxe** [comment]
@NicodeLee 不需要在 onSave 里做状态跟数据处理，加上 @State 是为了在横竖屏切换等情况下保存当前的 topicType
